# 生产环境 pro->production

# 网站端口
server:
  port: 80
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: root
    username: root
  # jpa 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  # 禁用缓存
  thymeleaf:
    cache: false


# 配置日志
logging:
  level:
    # 生产环境调高了日志级别
    root: warn
    com.predicated.blog: info
  file:
    path: log/blog-pro

